import manifest from '../data/art-manifest.json';

/**
 * Generated by scripts/art-import.mjs from the images in art/incoming.
 * Every raster asset is optional: when a name is missing the game draws its procedural art.
 */
export interface ArtFx { kind: 'smoke' | 'fire' | 'magic' | 'sparkle' | 'gold'; x: number; y: number }
export interface ArtEntry {
  file: string;
  /** pixel size of the stored image */
  w: number; h: number;
  /** display width in scene units (height follows the aspect ratio) */
  size: number;
  /** anchor (ground point) in 0..1 of the image */
  ax: number; ay: number;
  /** effect emitters in 0..1 image coordinates */
  fx?: ArtFx[];
}

const M = manifest as Record<string, ArtEntry>;
const BASE = (import.meta.env?.BASE_URL ?? './') + 'art/';

export function artEntry(name: string): ArtEntry | undefined { return M[name]; }
export function hasArt(name: string): boolean { return !!M[name]; }
export function artUrl(name: string): string { return BASE + M[name].file; }
export function artCount(): number { return Object.keys(M).length; }
