import { createRequire } from 'module'; const require = createRequire('/opt/node22/lib/node_modules/'); const { chromium } = require('playwright');
const out = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('404')) console.log('console:', m.text()); });
p.on('pageerror', (e) => console.log('pageerror:', e.message, e.stack));
await p.goto('http://localhost:5173/?new=order&skipintro');
await p.waitForTimeout(9000);
const shot = async (n, js, wait = 1200) => { if (js) { try { await p.evaluate(js); } catch (e) { console.log('ERR', n, e.message); } } await p.waitForTimeout(wait); await p.screenshot({ path: `${out}/${n}.png` }); };
await shot('t1_city');
await shot('t2_menu', `ga.city.select('barracks'); window.dispatchEvent(new Event('x')); window.bus.emit('city-select', {plot:'barracks'})`);
await shot('t3_train', `window.ui.open('train', {type:'barracks'})`);
await shot('t4_heroes', `const u=window.ui; u.closeAll(); u.open('heroes')`);
await shot('t5_tavern', `const u=window.ui; u.closeAll(); ga.game.s.inventory.key_gold=3; u.open('tavern')`);
await shot('t6_summon', `document.querySelectorAll('.btn.purple')[0].click()`, 2000);
await shot('t7_quests', `const u=window.ui; u.closeAll(); u.open('quests')`);
await shot('t8_world', `const u=window.ui; u.closeAll(); ga.setView('world')`, 2500);
await shot('t9_sheet', `const n=window.nav; n.goTo({kind:'world', find:'camp', level:1})`, 2500);
await shot('t10_dispatch', `document.querySelector('.sheet .btn.red').click()`, 1500);
await shot('t11_march', `document.querySelector('.panel .btn.red.big').click()`, 3000);
await p.waitForTimeout(30000);
await shot('t12_after', '', 500);
await shot('t13_report', `const u=window.ui; u.open('reports', {id: ga.game.s.reports.find(r=>r.kind==='battle')?.id})`, 6000);
await shot('t14_research', `const u=window.ui; u.closeAll(); ga.game.s.buildings.find(b=>b.type==='academy').level=3; u.open('research')`);
await shot('t15_inventory', `const u=window.ui; u.closeAll(); u.open('inventory')`);
await shot('t16_titans', `const u=window.ui; u.closeAll(); u.open('titans')`);
await shot('t17_army', `const u=window.ui; u.closeAll(); u.open('army')`);
await b.close();
